# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Ollama Install and start service
    before: echo "Hi from Terminal 2"
    init: curl -fsSL https://ollama.com/install.sh  | sh
    command: ollama serve 
  
  - name: install and set up the environment  
    init: pip install requests && pip install langchain-community && pip install langchain_chroma && pip install gradio && pip install --upgrade pypdf && ollama run llama3.1

 


# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Frontend
    description: Port 3000 for the frontend
    port: 3000
    onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart

